
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, font
from function import createaccount


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("900x640")
window.configure(bg = "#FFFFFF")
window.title("註冊")
# 設置字體大小和風格
custom_font = font.Font(family="Helvetica", size=20)


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 640,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    450.0,
    320.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    416.0,
    387.0,
    image=image_image_2
)

#輸入帳號
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    666.60693359375,
    387.4833068847656,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=custom_font
)
entry_1.place(
    x=524.0,
    y=360.0,
    width=285.2138671875,
    height=52.96661376953125
)

#輸入姓名
entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    666.60693359375,
    302.0932312011719,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=custom_font
)
entry_2.place(
    x=524.0,
    y=275.0,
    width=285.2138671875,
    height=52.18646240234375
)

#輸入密碼
entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    666.60693359375,
    470.75860595703125,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=custom_font
)
entry_3.place(
    x=524.0,
    y=443.0,
    width=285.2138671875,
    height=53.5172119140625
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: createaccount.create_account(entry_1.get(), entry_3.get(), entry_2.get() , window),
    relief="flat"
)
button_1.place(
    x=498.0,
    y=536.0,
    width=194.6233673095703,
    height=67.68318939208984
)


window.resizable(False, False)
window.mainloop()
