
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from function import homepage, globalfunction

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import os


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("900x640")
window.configure(bg = "#F0F0F0")
window.protocol("WM_DELETE_WINDOW", lambda: homepage.on_closing(window))# 将窗口关闭事件绑定到 on_closing 函数



canvas = Canvas(
    window,
    bg = "#F0F0F0",
    height = 640,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    593.0,
    320.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    408.88916015625,
    318.6012268066406,
    image=image_image_2
)

#開啟使用記錄
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: homepage.open_record_page(window),
    relief="flat"
)
button_1.place(
    x=471.23876953125,
    y=74.3558349609375,
    width=346.546142578125,
    height=99.63189697265625
)

#開啟個人資訊
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: homepage.open_logout(window),
    relief="flat"
)
button_2.place(
    x=471.23876953125,
    y=462.5766906738281,
    width=346.546142578125,
    height=99.63189697265625
)

#開啟統計圖表
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: homepage.open_statistical(window),
    relief="flat"
)
button_3.place(
    x=471.23876953125,
    y=209.71783447265625,
    width=346.546142578125,
    height=99.63189697265625
)

#開啟無人機資訊
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: homepage.open_drone_information(window),
    relief="flat"
)
button_4.place(
    x=471.23876953125,
    y=338.2085876464844,
    width=346.546142578125,
    height=99.63189697265625
)

#啟動無人機
button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: homepage.start_drone(window),
    relief="flat"
)
button_5.place(
    x=55.0,
    y=199.41104125976562,
    width=227.8939666748047,
    height=240.49078369140625
)
window.resizable(False, False)
window.mainloop()
