
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from function import login, globalfunction



# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, font, messagebox


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()

window.geometry("900x640")
window.configure(bg = "#F0F0F0")
window.title("登入")
custom_font= globalfunction.set_font()


canvas = Canvas(
    window,
    bg = "#F0F0F0",
    height = 640,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    448.0,
    319.0,
    image=image_image_1
)
#忘記密碼
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: login.open_forget_password(window),
    relief="flat"
)
button_1.place(
    x=572.6082763671875,
    y=396.0,
    width=104.3917236328125,
    height=22.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    621.0,
    300.0,
    image=image_image_2
)

#登入
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: login.open_home_page(window,entry_2.get(), entry_1.get()),
    relief="flat"
)
button_2.place(
    x=473.395263671875,
    y=319.99993896484375,
    width=302.3255920410156,
    height=61.19026565551758
)

#輸入密碼
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    658.720947265625,
    264.0708312988281,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=custom_font
)
entry_1.place(
    x=551.720947265625,
    y=240.0,
    width=214.0,
    height=46.14166259765625
)

#輸入帳號
entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    658.720947265625,
    189.79493713378906,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=custom_font
)
entry_2.place(
    x=551.720947265625,
    y=167.0,
    width=214.0,
    height=43.589874267578125
)

#建立帳號
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: login.open_create_account(window),
    relief="flat"
)
button_3.place(
    x=550.0849609375,
    y=442.3804626464844,
    width=146.4557647705078,
    height=46.93233871459961
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    248.162841796875,
    338.36151123046875,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
