import tkinter
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, font, messagebox, Label, font
from function import logout,homepage, globalfunction


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame10")



def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("900x640")
window.configure(bg = "#FFFFFF")
window.title("使用者資訊")
window.protocol("WM_DELETE_WINDOW", lambda: logout.on_closing(window))# 将窗口关闭事件绑定到 on_closing 函数

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 640,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    450.0,
    320.0,
    image=image_image_1
)

#回到主頁面
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: logout.back_to_homepage(window),#homepage.redisplay_homepage()),
    relief="flat"
)
button_1.place(
    x=24.0,
    y=21.0,
    width=137.5,
    height=38.75
)

#登出
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: logout.logout(window),#homepage.break_window()
    relief="flat"
)
button_2.place(
    x=471.0,
    y=551.0,
    width=101.0,
    height=45.0
)

#使用者帳號
label_1 = tkinter.Label(
    canvas,
    text=logout.get_username(),
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    font=("Helvetica", 20)  # 這裡可以調整字體和大小
)
label_1.place(
    x=530.0,
    y=365.0,
    width=355.0,
    height=66.75
)

#姓名
label_2 = tkinter.Label(
    canvas,
    text=logout.get_name(),
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    font=("Helvetica", 20)  # 這裡可以調整字體和大小
)
label_2.place(
    x=530.0,
    y=281.0,
    width=355.0,
    height=66.75
)

#編號
label_3 = tkinter.Label(
    canvas,
    text=logout.get_userID(),
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    font=("Helvetica", 20)  # 這裡可以調整字體和大小
)
label_3.place(
    x=530.0,
    y=449.75,
    width=355.0,
    height=66.75
)



window.resizable(False, False)
window.mainloop()
