
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from function import recordpage, globalfunction


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("900x640")
window.configure(bg = "#FFFFFF")
window.title("記錄選單")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 640,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    450.0,
    321.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    590.0,
    318.0,
    image=image_image_2
)

#開啟維護紀錄
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: recordpage.open_maintenance_record(window),
    relief="flat"
)
button_1.place(
    x=402.0,
    y=254.5,
    width=334.7975158691406,
    height=90.625
)

#生成完整報告
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: recordpage.create_report(),
    relief="flat"
)
button_2.place(
    x=403.852783203125,
    y=451.375,
    width=334.7975158691406,
    height=90.625
)

#開啟使用記錄
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: recordpage.open_usage_record(window),
    relief="flat"
)
button_3.place(
    x=403.852783203125,
    y=132.0,
    width=334.7975158691406,
    height=90.625
)

#回到主畫面
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: recordpage.back_to_homepage(window),
    relief="flat"
)
button_4.place(
    x=16.0,
    y=16.0,
    width=135.10067749023438,
    height=38.75
)
window.resizable(False, False)
window.mainloop()
