
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from function import usagerecord, globalfunction
from tkinter import ttk  # 導入 ttk 模組
from tkinter import simpledialog


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame5")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()


window.geometry("900x640")
window.configure(bg = "#FFFFFF")
window.title("使用紀錄")
window.protocol("WM_DELETE_WINDOW", lambda: usagerecord.on_closing(window))# 将窗口关闭事件绑定到 on_closing 函数

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 640,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    450.0,
    320.0,
    image=image_image_1
)

#回到主畫面
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: usagerecord.back_to_recordpage(window),
    relief="flat"
)
button_1.place(
    x=21.0,
    y=18.0,
    width=135.8956756591797,
    height=38.75
)

#新增資料
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: usagerecord.insert(),
    relief="flat"
)
button_2.place(
    x=34.0,
    y=557.0,
    width=209.40289306640625,
    height=57.5
)

#刪除資料
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: usagerecord.delete(window),
    relief="flat"
)
button_3.place(
    x=631.94091796875,
    y=557.0,
    width=209.40289306640625,
    height=57.5
)

#表格
# 定义列名
column_names = usagerecord.get_column_names()
# 从数据库获取数据
data_rows = usagerecord.get_table_value()

# 创建一个 Frame 用于包含 Treeview 和 Scrollbar
frame = ttk.Frame(window)
frame.place(x=75, y=85, width=750, height=400)
# 创建 Treeview 表格
tree = ttk.Treeview(frame, columns=column_names, show="headings")
tree.grid(row=0, column=0, sticky='nsew')
# 创建垂直滚动条
vscroll = ttk.Scrollbar(frame, orient="vertical", command=tree.yview)
vscroll.grid(row=0, column=1, sticky='ns')
# 创建横向滚动条
hscroll = ttk.Scrollbar(frame, orient="horizontal", command=tree.xview)
hscroll.grid(row=1, column=0, sticky='ew')
# 连接滚动条与 Treeview
tree.configure(yscrollcommand=vscroll.set, xscrollcommand=hscroll.set)
# 配置 frame 的 grid
frame.grid_columnconfigure(0, weight=1)  # 使 Treeview 列能扩展
frame.grid_rowconfigure(0, weight=1)  # 使 Treeview 行能扩展
# 创建一个 Style 对象并设定 Treeview 样式
style = ttk.Style(window)
style.configure("Treeview", font=('Helvetica', 12), rowheight=30)
style.configure("Treeview.Heading", font=('Helvetica', 14, 'bold'), anchor="center")
# 设置表格的列名和列宽
for i, column_name in enumerate(column_names):
    tree.heading(i, text=column_name)
    tree.column(i, width=160, anchor="center")  # 根据实际需求调整列宽
# 插入数据到 Treeview
for row in data_rows:
    tree.insert("", "end", values=row)

window.resizable(False, False)
window.mainloop()
